// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import (
	"github.com/chjoaquim/ride-service/internal/domain/passenger"
	mock "github.com/stretchr/testify/mock"
)

// PassengerRepository is an autogenerated mock type for the PassengerRepository type
type PassengerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: passenger
func (_m *PassengerRepository) Create(passenger *passenger.Passenger) (*passenger.Passenger, error) {
	ret := _m.Called(passenger)

	var r0 *passenger.Passenger
	var r1 error
	if rf, ok := ret.Get(0).(func(*passenger.Passenger) (*passenger.Passenger, error)); ok {
		return rf(passenger)
	}
	if rf, ok := ret.Get(0).(func(*passenger.Passenger) *passenger.Passenger); ok {
		r0 = rf(passenger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passenger.Passenger)
		}
	}

	if rf, ok := ret.Get(1).(func(*passenger.Passenger) error); ok {
		r1 = rf(passenger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *PassengerRepository) Get(id string) (*passenger.Passenger, error) {
	ret := _m.Called(id)

	var r0 *passenger.Passenger
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*passenger.Passenger, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *passenger.Passenger); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passenger.Passenger)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPassengerRepository creates a new instance of PassengerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPassengerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PassengerRepository {
	mock := &PassengerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
